CREATE SCHEMA EXERCISE1;
CREATE TABLE EMP_1
(EMP_NUM CHAR(3),
EMP_LNAME VARCHAR(15),
EMP_FNAME VARCHAR(15),
EMP_INITIAL CHAR(2),
EMP_HIREDATE DATE,
JOB_CODE CHAR(3));

INSERT INTO EMP_1(EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
VALUES ('1', 'LastName', 'FirstName', 'M', '2023-04-13', '501');
INSERT INTO EMP_1(EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
VALUES ('2', 'Meneses', 'Michael PauL', 'A', '2023-04-13', '502');

SELECT * FROM exercise1.emp_1
WHERE JOB_CODE = '502';